config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :news, only: [:create, :index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
  validates :title, :description, :url, :language, :categories, :countries, :slug, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news ||= NewsApi.new(filter_params).get_news
  end

  private

  def filter_params
    params.permit(:category, :country, :language)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news ||= News.all
  end

  def show
    @news = News.find(params[:id])
  end

  def create
    @news = News.new(news_params)
    if @news.save
      flash[:success] = "News is added your watch later list."
      redirect_to news_index_path
    else
      flash[:danger] = "Something went wrong."
    end
  end

  private

  def filter_params
    @filter_params ||= params.permit(:category, :country, :language)
  end

  def news_params
    @news_params ||= params.permit(:title, :description, :url, :slug)
  end

  def attributes
    news_params.merge(
      language: params[:language].split(","),
      categories: params[:categories].split(","),
      countries: params[:countries].split(",")
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def category_options
    [["Sports", "sports"], ["Entertainment", 'entertainment'], ["Business", 'business'], ["Science", "science"], ["Technology", "technology"], ["Health", "health"]]
  end

  def country_options
    [["India", "in"], ["USA", "us"], ["Japan", "jp"], ["UAE", "ae"]]
  end

  def language_options
    [["English", "en"], ["Hindi", "hi"], ["Arabic", "ar"], ["Japanese", "ja"]]
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<div class="container mt-3">
  <div class="row">
    <% @news.each do |news| %>
      <div class="col-md-4">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= news[:name] %></h5>
            <p class="card-text"><%= news[:description] %></p>
            <p class="card-text"><small class="text-muted"><a href=<%= news[:url]%>>Read More...</a></small></p>
            <%= form_for News.new, method: :post do %>
              <%= hidden_field_tag :title, news["name"] %>
              <%= hidden_field_tag :description, news["description"] %>
              <%= hidden_field_tag :language, news["language"].join(",") %>
              <%= hidden_field_tag :url, news["url"] %>
              <%= hidden_field_tag :slug, news["id"] %>
              <%= hidden_field_tag :categories, news["category"].join(",") %>
              <%= hidden_field_tag :countries, news["country"].join(",") %>
              <%= submit_tag "Read it later.", class: "btn btn-sm btn-outline-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Get Upto Date</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= form_tag root_path, method: :get, class: "form-inline" do %>
        <div class="input-group">
          <%= select_tag :category, options_for_select(category_options), class: "form-select" %>
          <%= select_tag :country, options_for_select(country_options), class: "form-select" %>
          <%= select_tag :language, options_for_select(language_options), class: "form-select" %>
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
      <% end %>
      <li class="nav-item active">
        <%= link_to "Read later news", news_index_path, class: "nav-link" %></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetUptoDate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/news/index.html.erb
<div class="container mt-3">
  <div class="row">
    <% @news.each do |news| %>
      <div class="col-md-4">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= news.title %></h5>
            <p class="card-text"><%= news.description %></p>
            <p class="card-text">
              <small class="text-muted">
                <a href=<%= news.url%>>Read More...</a>
              </small>
              <small class="text-muted">
                <%= link_to "Show", news_path(news), class: "btn btn-sm btn-outline-secondary"%>
              </small>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/news/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= @news.title %></h5>
          <p class="card-text"><%= @news.description %></p>
          <p class="card-text">
            <small class="text-muted">
              <a href=<%= @news.url%>>Read More...</a>
            </small>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>